[package]
name = "tapirus"
version = "1.0.3"
authors = ["t-sin <shinichi.tanaka45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.8.2"
num = "0.2"
rand = "0.6"
